### ISSUE TITLE
'generator' object has no attribute 'remove'报错

### ISSUE THREAD

**Issue by jcx70100** [arlenWKX/DaPengExport#1]
大佬您好，
下载您的代码执行后出现如下报错，还请指教，查询了一下google暂时没找到合适的修改方法，还请指点，感谢。

```
Traceback (most recent call last):
  File "./DaPengExport-main/main.py", line 324, in <module>
    c.getIP()
  File "./Downloads/DaPengExport-main/main.py", line 296, in getIP
    self.proxies = self.tpool.map(self.testproxy, self.raw_proxies).remove([])
AttributeError: 'generator' object has no attribute 'remove'
```

**Comment by arlenWKX** [comment]
这两天比较忙，已经改好了:smile:（详见注释）
